name: Lean CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Lean
      run: |
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
    
    - name: Install ripgrep
      run: sudo apt-get install -y ripgrep
    
    - name: Get mathlib cache
      run: lake exe cache get
      
    - name: Build project
      run: lake build
      
    - name: Check foundation integrity
      run: ./scripts/check_foundation.sh
      
    - name: Verify no sorries in non-ethics files
      run: |
        echo "Checking for sorries outside ethics/..."
        if find . -name "*.lean" -type f ! -path "./ethics/*" ! -path "./archive*/*" -exec grep -l "^[[:space:]]*sorry" {} \; | grep -v "^$"; then
          echo "❌ Found sorries in non-ethics files!"
          exit 1
        else
          echo "✅ No sorries found in non-ethics files"
        fi
